version: 2

models:
  - name: raw_customers
    description: "Customer dimension table containing customer details."
    columns:
      - name: customer_id
        description: "Unique identifier for each customer."
        tests:
          - unique
          - not_null
      - name: customer_name
        description: "Name of the customer."
      - name: customer_email
        description: "Email address of the customer."
      - name: location
        description: "Location of the customer."

  - name: raw_date
    description: "Date dimension table containing date and related components."
    columns:
      - name: date_id
        description: "Unique identifier for each date."
        tests:
          - unique
          - not_null
      - name: date
        description: "Date value."
        tests:
          - not_null
      - name: year
        description: "Year component of the date."
      - name: quarter
        description: "Quarter component of the date."
      - name: month
        description: "Month component of the date."
      - name: day
        description: "Day component of the date."

  - name: raw_product
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: product_name
        tests:
          - not_null
      - name: category
        tests:
          - not_null
      - name: price
        tests:
          - not null

  - name: raw_sales
    description: "Sales fact table containing transactional details."
    columns:
      - name: sale_id
        description: "Unique identifier for each sale transaction."
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key referencing customer."
        tests:
          - not_null
      - name: product_id
        description: "Foreign key referencing product."
        tests:
          - not_null
      - name: date_id
        description: "Foreign key referencing date."
        tests:
          - not_null
      - name: quantity
        description: "Quantity of product sold in the transaction."
      - name: total_amount
        description: "Total amount for the transaction after discounts."
        tests:
          - not_null
      - name: discount
        description: "Discount applied to the transaction."

  - name: stage_customers
    description: "Stage-level customer table after transformations."
    columns:
      - name: customer_id
        description: "Unique identifier for each customer."
        tests:
          - unique
          - not_null
      - name: customer_name
        description: "Name of the customer."
      - name: customer_email
        description: "Email address of the customer."
      - name: location
        description: "Location of the customer."

  - name: stage_date
    description: "Stage-level date table after transformations."
    columns:
      - name: date_id
        description: "Unique identifier for each date."
        tests:
          - unique
          - not_null
      - name: date
        description: "Date value."
        tests:
          - not_null
      - name: year
        description: "Year component of the date."
      - name: quarter
        description: "Quarter component of the date."
      - name: month
        description: "Month component of the date."
      - name: day
        description: "Day component of the date."

  - name: stage_product
    ccolumns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: product_name
        tests:
          - not_null
      - name: category
        tests:
          - not_null
      - name: price
        tests:
          - not null

  - name: stage_sales
    description: "Stage-level sales table after transformations."
    columns:
      - name: sale_id
        description: "Unique identifier for each sale transaction."
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key referencing customer."
        tests:
          - not_null
      - name: product_id
        description: "Foreign key referencing product."
        tests:
          - not_null
      - name: date_id
        description: "Foreign key referencing date."
        tests:
          - not_null
      - name: quantity
        description: "Quantity of product sold in the transaction."
      - name: total_amount
        description: "Total amount for the transaction after discounts."
        tests:
          - not_null
      - name: discount
        description: "Discount applied to the transaction."
